
export const PartnerOfferingSelectionSet = [
    'id',
    'offeringName',
    'contactInfo',
    'dashboard',
    'notes',
    'status.name',
    'nwnOffering.name',
    'nwnOffering.manager.name',
    'company.name',
    'priority.name',
    'apis.id',
    'apis.docLink',
    'apis.trainingLink',
    'apis.sandboxEnvironment',
    'apis.endpoint',
    'apis.apiType.name',
    'apis.authenticationType.name',
    'apis.authenticationInfo',
] as const;
